{{- if .Values.server.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "observability-analysis.fullname" . }}
  namespace: {{ include "observability-analysis.namespace" . }}
  labels:
    {{- include "observability-analysis.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
  {{- with .Values.server.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: {{ .Values.server.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "observability-analysis.serverSelectorLabels" . | nindent 4 }}
{{- end }}
